### Neural Networks

##### Importing necessary libraries

In [1]:
import pandas as pd
import numpy as np
import keras
from sklearn.preprocessing import StandardScaler

##### Loading dataset

In [2]:
df1=pd.read_csv(r'C:\Users\hp\Downloads\forestfires.csv')
df1.head()

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,0,1,0,0,0,0,small
1,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,0,0,0,0,0,0,1,0,small
2,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,0,0,0,0,0,0,1,0,small
3,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,0,1,0,0,0,0,small
4,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,0,1,0,0,0,0,small

##### EDA

In [3]:
df1.dtypes

month             object
day               object
FFMC             float64
DMC              float64
DC               float64
ISI              float64
temp             float64
RH                 int64
wind             float64
rain             float64
area             float64
dayfri             int64
daymon             int64
daysat             int64
daysun             int64
daythu             int64
daytue             int64
daywed             int64
monthapr           int64
monthaug           int64
monthdec           int64
monthfeb           int64
monthjan           int64
monthjul           int64
monthjun           int64
monthmar           int64
monthmay           int64
monthnov           int64
monthoct           int64
monthsep           int64
size_category     object
dtype: object

In [4]:
df1.shape

(517, 31)

In [5]:
df1.isnull().sum()

month            0
day              0
FFMC             0
DMC              0
DC               0
ISI              0
temp             0
RH               0
wind             0
rain             0
area             0
dayfri           0
daymon           0
daysat           0
daysun           0
daythu           0
daytue           0
daywed           0
monthapr         0
monthaug         0
monthdec         0
monthfeb         0
monthjan         0
monthjul         0
monthjun         0
monthmar         0
monthmay         0
monthnov         0
monthoct         0
monthsep         0
size_category    0
dtype: int64

In [6]:
df2=df1.drop(['month','day'],axis=1)
df2.head()

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0,1,...,0,0,0,0,1,0,0,0,0,small
1,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,small
2,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,small
3,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0,1,...,0,0,0,0,1,0,0,0,0,small
4,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0,0,...,0,0,0,0,1,0,0,0,0,small

##### Label Encoding

In [8]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [9]:
#Applying Label encoding to size_category column and adding result in new column named y
df2['size_category']=lb.fit_transform(df2['size_category'])
df2

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.00,1,...,0,0,0,0,1,0,0,0,0,1
1,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.00,0,...,0,0,0,0,0,0,0,1,0,1
2,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.00,0,...,0,0,0,0,0,0,0,1,0,1
3,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.00,1,...,0,0,0,0,1,0,0,0,0,1
4,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.00,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,6.44,0,...,0,0,0,0,0,0,0,0,0,0
513,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,54.29,0,...,0,0,0,0,0,0,0,0,0,0
514,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,11.16,0,...,0,0,0,0,0,0,0,0,0,0
515,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,0.00,0,...,0,0,0,0,0,0,0,0,0,1
516,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,0.00,0,...,0,0,0,0,0,0,1,0,0,1

In [10]:
df=df2.values
df.shape

(517, 29)

In [11]:
x=df[:,0:28]
y=df[:,-1]
x.shape

(517, 28)

##### Importing libraries for creating model

In [13]:
from sklearn.model_selection import GridSearchCV, KFold
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.optimizers import Adam

##### Creating Model

In [14]:
# create model
model = Sequential()
model.add(Dense(12, input_dim=28, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [15]:
model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])

In [16]:
model.fit(x, y, validation_split=0.33,epochs=100, batch_size=5)

Epoch 1/100
70/70 [==============================] - 89s 877ms/step - loss: 10.0180 - accuracy: 0.7139 - val_loss: 2.5327 - val_accuracy: 0.5556
Epoch 2/100
70/70 [==============================] - 2s 27ms/step - loss: 2.2049 - accuracy: 0.6879 - val_loss: 1.8387 - val_accuracy: 0.6608
Epoch 3/100
70/70 [==============================] - 2s 23ms/step - loss: 1.7317 - accuracy: 0.7601 - val_loss: 1.6152 - val_accuracy: 0.6901
Epoch 4/100
70/70 [==============================] - 1s 19ms/step - loss: 1.4353 - accuracy: 0.7890 - val_loss: 2.0320 - val_accuracy: 0.7076
Epoch 5/100
70/70 [==============================] - 1s 19ms/step - loss: 1.2555 - accuracy: 0.8179 - val_loss: 1.2349 - val_accuracy: 0.7368
Epoch 6/100
70/70 [==============================] - 1s 19ms/step - loss: 1.1209 - accuracy: 0.8064 - val_loss: 1.0241 - val_accuracy: 0.7544
Epoch 7/100
70/70 [==============================] - 1s 21ms/step - loss: 0.9464 - accuracy: 0.8006 - val_loss: 1.0719 - val_accuracy: 0.7427
Epoch 8/100
70/70 [==============================] - 1s 21ms/step - loss: 0.8020 - accuracy: 0.8468 - val_loss: 0.8393 - val_accuracy: 0.7719
Epoch 9/100
70/70 [==============================] - 1s 17ms/step - loss: 0.6745 - accuracy: 0.8497 - val_loss: 0.7369 - val_accuracy: 0.7778
Epoch 10/100
70/70 [==============================] - 2s 29ms/step - loss: 0.5648 - accuracy: 0.8699 - val_loss: 0.7686 - val_accuracy: 0.8012
Epoch 11/100
70/70 [==============================] - 3s 47ms/step - loss: 0.4507 - accuracy: 0.8699 - val_loss: 0.7460 - val_accuracy: 0.7953: 0
Epoch 12/100
70/70 [==============================] - 2s 23ms/step - loss: 0.4026 - accuracy: 0.8699 - val_loss: 0.5588 - val_accuracy: 0.8129
Epoch 13/100
70/70 [==============================] - 1s 21ms/step - loss: 0.3358 - accuracy: 0.8815 - val_loss: 0.5285 - val_accuracy: 0.8187
Epoch 14/100
70/70 [==============================] - 1s 18ms/step - loss: 0.3111 - accuracy: 0.8757 - val_loss: 0.5097 - val_accuracy: 0.8246
Epoch 15/100
70/70 [==============================] - 2s 22ms/step - loss: 0.2718 - accuracy: 0.8902 - val_loss: 0.5106 - val_accuracy: 0.8246
Epoch 16/100
70/70 [==============================] - 3s 41ms/step - loss: 0.2646 - accuracy: 0.8960 - val_loss: 0.6331 - val_accuracy: 0.8129
Epoch 17/100
70/70 [==============================] - 3s 47ms/step - loss: 0.2857 - accuracy: 0.8931 - val_loss: 0.4508 - val_accuracy: 0.8421
Epoch 18/100
70/70 [==============================] - 3s 45ms/step - loss: 0.2430 - accuracy: 0.9075 - val_loss: 0.4023 - val_accuracy: 0.8304A: 0s - loss: 0.230
Epoch 19/100
70/70 [==============================] - 2s 24ms/step - loss: 0.2594 - accuracy: 0.9046 - val_loss: 0.5619 - val_accuracy: 0.8129
Epoch 20/100
70/70 [==============================] - 2s 34ms/step - loss: 0.2742 - accuracy: 0.8988 - val_loss: 0.4178 - val_accuracy: 0.8421
Epoch 21/100
70/70 [==============================] - 5s 67ms/step - loss: 0.2264 - accuracy: 0.9335 - val_loss: 0.6407 - val_accuracy: 0.8070
Epoch 22/100
70/70 [==============================] - 2s 26ms/step - loss: 0.2689 - accuracy: 0.8902 - val_loss: 0.3320 - val_accuracy: 0.8655
Epoch 23/100
70/70 [==============================] - 1s 20ms/step - loss: 0.2066 - accuracy: 0.9220 - val_loss: 0.2920 - val_accuracy: 0.8830
Epoch 24/100
70/70 [==============================] - 2s 25ms/step - loss: 0.2155 - accuracy: 0.9306 - val_loss: 0.4855 - val_accuracy: 0.8187
Epoch 25/100
70/70 [==============================] - 2s 26ms/step - loss: 0.1852 - accuracy: 0.9335 - val_loss: 0.5554 - val_accuracy: 0.8187
Epoch 26/100
70/70 [==============================] - 3s 46ms/step - loss: 0.2183 - accuracy: 0.9249 - val_loss: 0.4543 - val_accuracy: 0.8246
Epoch 27/100
70/70 [==============================] - 2s 21ms/step - loss: 0.1865 - accuracy: 0.9277 - val_loss: 0.3218 - val_accuracy: 0.8655
Epoch 28/100
70/70 [==============================] - 1s 20ms/step - loss: 0.1933 - accuracy: 0.9335 - val_loss: 0.3331 - val_accuracy: 0.8538
Epoch 29/100
70/70 [==============================] - 3s 43ms/step - loss: 0.2324 - accuracy: 0.9191 - val_loss: 0.3125 - val_accuracy: 0.8655
Epoch 30/100
70/70 [==============================] - 2s 27ms/step - loss: 0.1700 - accuracy: 0.9451 - val_loss: 0.2936 - val_accuracy: 0.8713
Epoch 31/100
70/70 [==============================] - 4s 52ms/step - loss: 0.1773 - accuracy: 0.9422 - val_loss: 0.3115 - val_accuracy: 0.8596
Epoch 32/100
70/70 [==============================] - 2s 26ms/step - loss: 0.2010 - accuracy: 0.9191 - val_loss: 0.2902 - val_accuracy: 0.9298
Epoch 33/100
70/70 [==============================] - 1s 19ms/step - loss: 0.1729 - accuracy: 0.9364 - val_loss: 0.2905 - val_accuracy: 0.8713
Epoch 34/100
70/70 [==============================] - 1s 17ms/step - loss: 0.1602 - accuracy: 0.9451 - val_loss: 0.3674 - val_accuracy: 0.8421
Epoch 35/100
70/70 [==============================] - 2s 22ms/step - loss: 0.1570 - accuracy: 0.9393 - val_loss: 0.2273 - val_accuracy: 0.9006
Epoch 36/100
70/70 [==============================] - 2s 32ms/step - loss: 0.1466 - accuracy: 0.9451 - val_loss: 0.2568 - val_accuracy: 0.8830
Epoch 37/100
70/70 [==============================] - 5s 66ms/step - loss: 0.1473 - accuracy: 0.9422 - val_loss: 0.1974 - val_accuracy: 0.9064
70/70 [==============================] - 4s 54ms/step - loss: 0.0415 - accuracy: 0.9942 - val_loss: 0.0901 - val_accuracy: 0.9708
Epoch 88/100
70/70 [==============================] - 3s 41ms/step - loss: 0.0478 - accuracy: 0.9913 - val_loss: 0.0883 - val_accuracy: 0.9708
Epoch 89/100
70/70 [==============================] - 2s 34ms/step - loss: 0.0407 - accuracy: 0.9942 - val_loss: 0.0837 - val_accuracy: 0.9766
Epoch 90/100
70/70 [==============================] - 2s 30ms/step - loss: 0.0448 - accuracy: 0.9884 - val_loss: 0.0911 - val_accuracy: 0.9591
Epoch 91/100
70/70 [==============================] - 3s 44ms/step - loss: 0.0550 - accuracy: 0.9798 - val_loss: 0.0940 - val_accuracy: 0.9591
Epoch 92/100
70/70 [==============================] - 3s 38ms/step - loss: 0.0583 - accuracy: 0.9740 - val_loss: 0.0991 - val_accuracy: 0.9591
Epoch 93/100
70/70 [==============================] - 2s 33ms/step - loss: 0.0572 - accuracy: 0.9769 - val_loss: 0.0833 - val_accuracy: 0.9708
Epoch 94/100
70/70 [==============================] - 2s 28ms/step - loss: 0.0398 - accuracy: 0.9855 - val_loss: 0.0832 - val_accuracy: 0.9708
Epoch 95/100
70/70 [==============================] - 4s 59ms/step - loss: 0.0516 - accuracy: 0.9769 - val_loss: 0.1125 - val_accuracy: 0.9532
Epoch 96/100
70/70 [==============================] - 2s 32ms/step - loss: 0.0374 - accuracy: 0.9913 - val_loss: 0.0792 - val_accuracy: 0.9766
Epoch 97/100
70/70 [==============================] - 2s 32ms/step - loss: 0.0593 - accuracy: 0.9827 - val_loss: 0.2345 - val_accuracy: 0.9064
Epoch 98/100
70/70 [==============================] - 4s 51ms/step - loss: 0.0490 - accuracy: 0.9827 - val_loss: 0.3259 - val_accuracy: 0.8830
Epoch 99/100
70/70 [==============================] - 7s 100ms/step - loss: 0.0670 - accuracy: 0.9827 - val_loss: 0.0786 - val_accuracy: 0.9708
Epoch 100/100
70/70 [==============================] - 3s 46ms/step - loss: 0.0444 - accuracy: 0.9884 - val_loss: 0.0745 - val_accuracy: 0.9766

##### Accuracy

In [18]:
# evaluate the model
scores = model.evaluate(x,y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

17/17 [==============================] - 0s 13ms/step - loss: 0.0439 - accuracy: 0.9884
accuracy: 98.84%

##### Inference
- The model is a good predictor for the burned area of Forest Fires